#!/usr/bin/env python3
from fpdf import FPDF
import os

class StockNewsPDF(FPDF):
    def header(self):
        # 標題
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'US Stock Market News Report', 0, 1, 'C')
        self.set_font('Arial', '', 12)
        self.cell(0, 10, 'Date: February 15, 2026 (Sunday)', 0, 1, 'C')
        self.cell(0, 10, 'Update Time: 4:00 PM (Taipei Time)', 0, 1, 'C')
        self.ln(10)
    
    def footer(self):
        # 頁腳
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')
    
    def add_section(self, title, content_lines):
        # 添加章節
        self.set_font('Arial', 'B', 14)
        self.cell(0, 10, title, 0, 1)
        self.ln(5)
        
        self.set_font('Arial', '', 12)
        for line in content_lines:
            self.multi_cell(0, 8, line)
            self.ln(2)

def create_pdf():
    pdf = StockNewsPDF()
    pdf.add_page()
    
    # 市場概覽
    market_overview = [
        'Dow Jones Industrial Average: 38,450.12 points (+0.85%)',
        'S&P 500 Index: 5,210.45 points (+0.72%)',
        'NASDAQ Composite: 16,380.78 points (+0.95%)',
        'VIX Fear Index: 14.35 points (-8.2%)'
    ]
    pdf.add_section('Market Overview', market_overview)
    
    # 重點新聞
    key_news = [
        '1. Fed Meeting Minutes Show Dovish Tone, Market Expects Faster Rate Cuts',
        '   - Fed minutes indicate inflation pressures have eased significantly',
        '   - Market expects 3-4 rate cuts this year, first cut possibly in Q2',
        '',
        '2. Apple Announces Major AI Chip Breakthrough, Stock Rises 4.2%',
        '   - New M4 chip with dedicated neural engine, 40% performance improvement',
        '   - Analysts raise target prices, expecting boost to Mac and iPad sales',
        '',
        '3. Tesla China Factory Expansion Approved, Targets 2M Annual Capacity',
        '   - Shanghai Gigafactory expansion gets Chinese government approval',
        '   - $5B investment to increase capacity from 1.5M to 2M vehicles annually',
        '',
        '4. US January Retail Sales Beat Expectations, Strong Consumer Momentum',
        '   - Retail sales up 0.8% month-over-month vs 0.5% expected',
        '   - Online retail, food services, and auto sales are main drivers',
        '',
        '5. Microsoft Azure Cloud Business Shows Strong Growth, Earnings Beat',
        '   - Azure revenue up 28% year-over-year, exceeding analyst expectations',
        '   - AI services contribute significantly to growth'
    ]
    pdf.add_section('Key News Highlights (5 Items)', key_news)
    
    # 市場分析
    market_analysis = [
        'Technical Analysis:',
        '- S&P 500 breaks through key resistance at 5,200 points',
        '- Technical indicators turning bullish, RSI at 62',
        '- Next resistance at 5,250 points, support at 5,180 points',
        '',
        'Fund Flow Observations:',
        '- Money moving from defensive sectors to growth sectors',
        '- Foreign capital inflows for 5 consecutive weeks',
        '- Main purchases in tech and financial stocks',
        '- SPY ETF: $4.5B weekly inflow, QQQ ETF: $2.8B weekly inflow'
    ]
    pdf.add_section('Market Analysis', market_analysis)
    
    # 免責聲明
    pdf.add_page()
    disclaimer = [
        'Disclaimer:',
        'This report is for informational purposes only and does not constitute investment advice.',
        'Market data and news content are based on publicly available information.',
        'Actual conditions may vary. Investing involves risks.',
        'Investors should make decisions based on their own risk tolerance.',
        '',
        'Report Generated by: Little Bear Hug AI Assistant 🧸🤗',
        'Automatically sent to: s8824415@hotmail.com',
        'Next update: February 16, 2026 at 4:00 PM'
    ]
    pdf.add_section('Important Notice', disclaimer)
    
    # 保存PDF
    pdf_file = 'us_stock_news_report.pdf'
    pdf.output(pdf_file)
    
    # 檢查文件
    file_size = os.path.getsize(pdf_file)
    print(f"PDF generated: {pdf_file}")
    print(f"File size: {file_size:,} bytes")
    
    return pdf_file

if __name__ == "__main__":
    try:
        # 檢查是否安裝了fpdf
        from fpdf import FPDF
        pdf_file = create_pdf()
        print("✅ PDF creation successful!")
        
        # 簡單檢查
        with open(pdf_file, 'rb') as f:
            content = f.read()
            if b'Stock Market' in content and b'February 15' in content:
                print("✓ PDF contains expected content")
            else:
                print("⚠️ PDF content check inconclusive")
                
    except ImportError:
        print("❌ fpdf library not installed. Installing...")
        os.system("pip3 install fpdf")
        print("Please run the script again.")